export const chatListMockData = [
    "How to Train Your Brain",
    "Top 10 Mysteries of the",
    "The Future of Artificial",
    "The Hidden Benefits",
    "How Do Animals Understand",
    "Exploring the Concept of",
    "The Science Behind",
    "Can Machines Truly",
    "The History and Evolution",
    "How to Build Stronger",
    "Uncovering the Secrets",
    "How to Master Time",
    "The Power of Positive",
    "Exploring the Limits",
    "The Science of Happiness",
    "How Does Artificial",
    "The Role of Music in",
    "What Happens When You",
    "Why Do We Love Stories?",
    "The Future of Space",
    "The Art of Being Present",
    "How Climate Change Affects",
    "What Is Quantum Computing",
    "Understanding the Psychology",
    "The Mysteries of Deep"
  ];
